name: "Continous Integration"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  precommit:
    name: Pre-Commit
    runs-on: ubuntu-20.04
    steps:
      - name: AtomiCloud CI Environment
        uses: AtomiCloud/atomici-ns-action@v1.0.0
        with:
          namespacelabs: "false"

      - name: Run Pre-commit checks
        run: nix develop .#ci -c scripts/ci/pre-commit.sh
