name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      # - name: AtomiCloud CI Environment
      #   uses: AtomiCloud/atomici-ns-action@v1.1.0
      #   with:
      #     namespacelabs: "false"
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix develop .#releaser -c scripts/ci/release.sh
